version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somedrupal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

  drupal:
    depends_on:
      - db
    image: drupal:${DRUPAL_IMAGE_VERSION}
    ports:
      - 8000:80
    volumes:
      - web_data:/var/www/html
volumes:
  db_data:
  web_data:
